const products = [
  {
    id: 1,
    name: "Floral Summer Dress",
    brand: "Zara",
    category: "Dresses",
    gender: "Women",
    price: 2499,
    originalPrice: 3499,
    discount: "29% OFF",
    rating: 4.8,
    reviewCount: 126,
    image:
      "https://i.pinimg.com/1200x/8a/13/f0/8a13f073038b49adee65d71fb14c8711.jpg",
    isBestSeller: true,
    description:
      "Lightweight floral dress perfect for summer outings and casual occasions.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Yellow", "White", "Pink"],
    material: "100% Cotton",
    fit: "Regular Fit",
    careInstructions: ["Machine wash cold", "Do not bleach"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [
      { user: "Ananya", rating: 5, comment: "Very comfortable and stylish." },
      { user: "Sneha", rating: 4, comment: "Color is beautiful." },
    ],
  },

  {
    id: 2,
    name: "Casual Denim Jacket",
    brand: "H&M",
    category: "Jackets",
    gender: "Women",
    price: 3499,
    originalPrice: 4499,
    discount: "22% OFF",
    rating: 4.6,
    reviewCount: 98,
    image:
      "https://i.pinimg.com/736x/55/26/9b/55269b0adcb31a2d055abf8410e207d2.jpg",
    isBestSeller: true,
    description:
      "Classic denim jacket suitable for all seasons and easy layering.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
    material: "Denim Cotton Blend",
    fit: "Slim Fit",
    careInstructions: ["Machine wash inside out", "Dry in shade"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Riya", rating: 5, comment: "Premium quality jacket." }],
  },

  {
    id: 3,
    name: "High Waist Skinny Jeans",
    brand: "Levi's",
    category: "Jeans",
    gender: "Women",
    price: 1999,
    originalPrice: 2499,
    discount: "20% OFF",
    rating: 4.5,
    reviewCount: 112,
    image:
      "https://i.pinimg.com/1200x/4a/6f/d3/4a6fd3aa973d2ca155f5c1478c797280.jpg",
    isBestSeller: false,
    description: "High-waist skinny jeans with stretch for all-day comfort.",
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Dark Blue", "Black"],
    material: "Denim Elastane Blend",
    fit: "Skinny Fit",
    careInstructions: ["Machine wash cold", "Do not tumble dry"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Pooja", rating: 4, comment: "Great fit and stretch." }],
  },

  {
    id: 4,
    name: "Elegant Evening Gown",
    brand: "Forever 21",
    category: "Gowns",
    gender: "Women",
    price: 7499,
    originalPrice: 8999,
    discount: "17% OFF",
    rating: 4.9,
    reviewCount: 64,
    image:
      "https://i.pinimg.com/1200x/a1/6e/6b/a16e6b236933bb8180176d0b229017e9.jpg",
    isBestSeller: true,
    description:
      "Elegant floor-length gown designed for parties and special events.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Black", "Navy"],
    material: "Polyester Satin",
    fit: "Slim Fit",
    careInstructions: ["Dry clean only"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 5–7 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Kavya", rating: 5, comment: "Looks stunning!" }],
  },

  {
    id: 5,
    name: "Striped Casual Top",
    brand: "Uniqlo",
    category: "Tops",
    gender: "Women",
    price: 1299,
    originalPrice: 1799,
    discount: "28% OFF",
    rating: 4.4,
    reviewCount: 87,
    image:
      "https://i.pinimg.com/736x/22/16/dc/2216dc201c7a3deca9afb180e3586cfb.jpg",
    isBestSeller: false,
    description: "Soft striped top ideal for daily wear and casual styling.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Blue"],
    material: "Cotton Blend",
    fit: "Regular Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Neha", rating: 4, comment: "Good fabric quality." }],
  },
  {
    id: 6,
    name: "Leather Handbag",
    brand: "Michael Kors",
    category: "Bags",
    gender: "Women",
    price: 4999,
    originalPrice: 5999,
    discount: "17% OFF",
    rating: 4.7,
    reviewCount: 143,
    image:
      "https://i.pinimg.com/1200x/5c/7f/fc/5c7ffcd88ec3a3189f792c10faccbd75.jpg",
    isBestSeller: true,
    description:
      "Premium leather handbag with spacious compartments for everyday elegance.",
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Tan"],
    material: "Genuine Leather",
    fit: "Structured",
    careInstructions: ["Wipe with dry cloth", "Avoid water"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Megha", rating: 5, comment: "Looks luxurious!" }],
  },

  {
    id: 7,
    name: "Silk Scarf",
    brand: "Hermès",
    category: "Accessories",
    gender: "Women",
    price: 899,
    originalPrice: 1299,
    discount: "31% OFF",
    rating: 4.8,
    reviewCount: 76,
    image:
      "https://i.pinimg.com/1200x/74/1b/52/741b5257103856ce28adac018daa67bd.jpg",
    isBestSeller: false,
    description: "Soft silk scarf that adds a refined touch to any outfit.",
    sizes: ["Free Size"],
    colors: ["Multicolor"],
    material: "100% Silk",
    fit: "Relaxed",
    careInstructions: ["Dry clean only"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Isha", rating: 5, comment: "Very classy!" }],
  },

  {
    id: 8,
    name: "Classic Pumps",
    brand: "Steve Madden",
    category: "Footwear",
    gender: "Women",
    price: 3499,
    originalPrice: 4299,
    discount: "18% OFF",
    rating: 4.6,
    reviewCount: 94,
    image:
      "https://i.pinimg.com/736x/af/79/5d/af795dcd196eecec1fcc1315f4a64eba.jpg",
    isBestSeller: true,
    description: "Elegant pumps perfect for office wear and formal occasions.",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Black", "Nude"],
    material: "Synthetic Leather",
    fit: "Standard Fit",
    careInstructions: ["Clean with soft cloth"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Aarti", rating: 4, comment: "Comfortable heels." }],
  },

  {
    id: 9,
    name: "Chunky Knit Sweater",
    brand: "H&M",
    category: "Sweaters",
    gender: "Women",
    price: 2199,
    originalPrice: 2799,
    discount: "22% OFF",
    rating: 4.5,
    reviewCount: 101,
    image:
      "https://i.pinimg.com/736x/81/85/a9/8185a9b02f20af478307cc0d734d8e07.jpg",
    isBestSeller: true,
    description: "Warm chunky knit sweater ideal for winter layering.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Grey"],
    material: "Wool Blend",
    fit: "Relaxed Fit",
    careInstructions: ["Hand wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Divya", rating: 5, comment: "Very cozy!" }],
  },

  {
    id: 10,
    name: "Pleated Midi Skirt",
    brand: "Zara",
    category: "Skirts",
    gender: "Women",
    price: 2999,
    originalPrice: 3699,
    discount: "19% OFF",
    rating: 4.7,
    reviewCount: 88,
    image:
      "https://i.pinimg.com/736x/bb/2a/9c/bb2a9cd42594e44207309df704de3e92.jpg",
    isBestSeller: false,
    description:
      "Flowy pleated midi skirt suitable for both casual and formal looks.",
    sizes: ["S", "M", "L"],
    colors: ["Cream", "Olive"],
    material: "Polyester",
    fit: "Regular Fit",
    careInstructions: ["Machine wash gentle"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Lavanya", rating: 5, comment: "Very elegant." }],
  },
  {
    id: 11,
    name: "Off-Shoulder Ruffle Top",
    brand: "Forever 21",
    category: "Tops",
    gender: "Women",
    price: 1599,
    originalPrice: 1999,
    discount: "20% OFF",
    rating: 4.5,
    reviewCount: 72,
    image:
      "https://i.pinimg.com/1200x/0c/4a/57/0c4a571bc2ad63759f0173384b5b3ba0.jpg",
    isBestSeller: true,
    description:
      "Trendy off-shoulder top with soft ruffles for a chic summer look.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Pink"],
    material: "Cotton Blend",
    fit: "Slim Fit",
    careInstructions: ["Machine wash cold", "Do not bleach"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Keerthi", rating: 5, comment: "Very stylish!" }],
  },

  {
    id: 12,
    name: "Maxi Boho Dress",
    brand: "H&M",
    category: "Dresses",
    gender: "Women",
    price: 3299,
    originalPrice: 3999,
    discount: "18% OFF",
    rating: 4.8,
    reviewCount: 119,
    image:
      "https://i.pinimg.com/736x/75/ec/c1/75ecc174f56f2796f332e45ce4473a73.jpg",
    isBestSeller: true,
    description:
      "Bohemian-style maxi dress perfect for vacations and beach outings.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Maroon"],
    material: "Rayon",
    fit: "Flowy Fit",
    careInstructions: ["Hand wash recommended"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Pavani", rating: 5, comment: "Love the boho vibe!" }],
  },

  {
    id: 13,
    name: "Leather Belt Bag",
    brand: "Coach",
    category: "Bags",
    gender: "Women",
    price: 2199,
    originalPrice: 2699,
    discount: "18% OFF",
    rating: 4.6,
    reviewCount: 65,
    image:
      "https://i.pinimg.com/1200x/41/d4/6a/41d46a84a7a08a70a99cfc47a319d7ee.jpg",
    isBestSeller: false,
    description: "Compact leather belt bag ideal for travel and casual wear.",
    sizes: ["One Size"],
    colors: ["Black", "Tan"],
    material: "Genuine Leather",
    fit: "Adjustable",
    careInstructions: ["Wipe clean with dry cloth"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [
      { user: "Roshni", rating: 4, comment: "Very handy and stylish." },
    ],
  },

  {
    id: 14,
    name: "Casual Hoodie",
    brand: "Nike",
    category: "Hoodies",
    gender: "Women",
    price: 1899,
    originalPrice: 2399,
    discount: "21% OFF",
    rating: 4.4,
    reviewCount: 104,
    image:
      "https://i.pinimg.com/1200x/47/a2/5a/47a25ade097710369190f4b99cad6e9c.jpg",
    isBestSeller: true,
    description:
      "Comfortable casual hoodie perfect for daily wear and workouts.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Black"],
    material: "Cotton Fleece",
    fit: "Relaxed Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Siri", rating: 5, comment: "Very comfortable." }],
  },

  {
    id: 15,
    name: "Wide-Leg Palazzo Pants",
    brand: "Zara",
    category: "Pants",
    gender: "Women",
    price: 2499,
    originalPrice: 3199,
    discount: "22% OFF",
    rating: 4.7,
    reviewCount: 89,
    image:
      "https://i.pinimg.com/736x/96/e4/4e/96e44e8ba167aa4173cb1af4c4be780e.jpg",
    isBestSeller: true,
    description: "Elegant wide-leg palazzo pants offering comfort and style.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Beige"],
    material: "Poly Crepe",
    fit: "Loose Fit",
    careInstructions: ["Machine wash gentle"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Nandini", rating: 5, comment: "Perfect office wear." }],
  },

  {
    id: 16,
    name: "Cotton Tunic Top",
    brand: "Uniqlo",
    category: "Tops",
    gender: "Women",
    price: 1399,
    originalPrice: 1799,
    discount: "22% OFF",
    rating: 4.5,
    reviewCount: 77,
    image:
      "https://i.pinimg.com/1200x/7a/30/90/7a3090de8839a3633ed0411af82903d5.jpg",
    isBestSeller: false,
    description: "Breathable cotton tunic top suitable for daily wear.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Pastel Green"],
    material: "100% Cotton",
    fit: "Regular Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Bhavana", rating: 4, comment: "Soft fabric." }],
  },

  {
    id: 17,
    name: "Strappy Sandals",
    brand: "Steve Madden",
    category: "Footwear",
    gender: "Women",
    price: 1999,
    originalPrice: 2499,
    discount: "20% OFF",
    rating: 4.6,
    reviewCount: 91,
    image:
      "https://i.pinimg.com/1200x/de/d6/06/ded606f491d26133a5c0627741d64196.jpg",
    isBestSeller: true,
    description: "Stylish strappy sandals for casual and party wear.",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Black", "Gold"],
    material: "Synthetic Leather",
    fit: "Comfort Fit",
    careInstructions: ["Wipe with soft cloth"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Aishwarya", rating: 5, comment: "Very comfortable." }],
  },

  {
    id: 18,
    name: "Denim Shorts",
    brand: "Levi's",
    category: "Shorts",
    gender: "Women",
    price: 1299,
    originalPrice: 1799,
    discount: "28% OFF",
    rating: 4.5,
    reviewCount: 68,
    image:
      "https://i.pinimg.com/736x/3d/cc/68/3dcc681041f4b1f3fddf5cd9f8061315.jpg",
    isBestSeller: false,
    description: "Comfortable denim shorts perfect for summer outings.",
    sizes: ["26", "28", "30", "32"],
    colors: ["Light Blue"],
    material: "Denim Cotton",
    fit: "Regular Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Harini", rating: 4, comment: "Good quality denim." }],
  },

  {
    id: 19,
    name: "Chiffon Layered Skirt",
    brand: "H&M",
    category: "Skirts",
    gender: "Women",
    price: 2499,
    originalPrice: 3199,
    discount: "22% OFF",
    rating: 4.7,
    reviewCount: 83,
    image:
      "https://i.pinimg.com/1200x/f4/47/7e/f4477e48a390509eeb382fdd15e360ab.jpg",
    isBestSeller: true,
    description:
      "Elegant chiffon skirt with layered design for a graceful look.",
    sizes: ["S", "M", "L"],
    colors: ["Peach", "Black"],
    material: "Chiffon Polyester",
    fit: "Flowy Fit",
    careInstructions: ["Hand wash recommended"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Sowmya", rating: 5, comment: "Very elegant skirt." }],
  },

  {
    id: 20,
    name: "Faux Leather Jacket",
    brand: "Zara",
    category: "Jackets",
    gender: "Women",
    price: 3999,
    originalPrice: 4999,
    discount: "20% OFF",
    rating: 4.8,
    reviewCount: 132,
    image:
      "https://i.pinimg.com/1200x/6e/3b/6c/6e3b6cff7af0c7e6445103d02f2bef5e.jpg",
    isBestSeller: true,
    description: "Trendy faux leather jacket for bold and modern styling.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
    material: "Faux Leather",
    fit: "Slim Fit",
    careInstructions: ["Wipe clean only"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Tejaswini", rating: 5, comment: "Looks premium!" }],
  },
  {
    id: 21,
    name: "Sequin Party Dress",
    brand: "Forever 21",
    category: "Dresses",
    gender: "Women",
    price: 4599,
    originalPrice: 5999,
    discount: "23% OFF",
    rating: 4.9,
    reviewCount: 57,
    image:
      "https://i.pinimg.com/736x/fa/9e/5b/fa9e5b06d9565bfab508786020b1343f.jpg",
    isBestSeller: true,
    description: "Glamorous sequin dress perfect for parties and night events.",
    sizes: ["S", "M", "L"],
    colors: ["Silver", "Black"],
    material: "Sequin Polyester",
    fit: "Slim Fit",
    careInstructions: ["Dry clean only"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 5–7 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Shruthi", rating: 5, comment: "Perfect party dress!" }],
  },

  {
    id: 22,
    name: "Pleated Mini Skirt",
    brand: "Zara",
    category: "Skirts",
    gender: "Women",
    price: 1999,
    originalPrice: 2499,
    discount: "20% OFF",
    rating: 4.6,
    reviewCount: 73,
    image:
      "https://i.pinimg.com/736x/81/00/d1/8100d18b7ef81a72d4717bd2a5f2a591.jpg",
    isBestSeller: false,
    description: "Stylish pleated mini skirt for casual and semi-formal wear.",
    sizes: ["S", "M", "L"],
    colors: ["Grey", "Black"],
    material: "Polyester",
    fit: "Regular Fit",
    careInstructions: ["Machine wash gentle"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Anjali", rating: 4, comment: "Very trendy." }],
  },

  {
    id: 23,
    name: "Crop Top with Lace",
    brand: "H&M",
    category: "Tops",
    gender: "Women",
    price: 1499,
    originalPrice: 1999,
    discount: "25% OFF",
    rating: 4.5,
    reviewCount: 69,
    image:
      "https://i.pinimg.com/1200x/4c/4a/ab/4c4aab941f0480367d9c42299acf090c.jpg",
    isBestSeller: true,
    description:
      "Stylish lace-detailed crop top ideal for casual and party looks.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black"],
    material: "Cotton Lace Blend",
    fit: "Slim Fit",
    careInstructions: ["Hand wash recommended"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Manasa", rating: 5, comment: "Looks amazing!" }],
  },

  {
    id: 24,
    name: "Pleated Maxi Skirt",
    brand: "Forever 21",
    category: "Skirts",
    gender: "Women",
    price: 3299,
    originalPrice: 3999,
    discount: "18% OFF",
    rating: 4.7,
    reviewCount: 84,
    image:
      "https://i.pinimg.com/736x/56/b7/b5/56b7b5823841ca7d787dda0e5b7cfb40.jpg",
    isBestSeller: true,
    description: "Flowy pleated maxi skirt offering elegance and comfort.",
    sizes: ["S", "M", "L"],
    colors: ["Beige", "Wine"],
    material: "Polyester",
    fit: "Flowy Fit",
    careInstructions: ["Machine wash gentle"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Swetha", rating: 5, comment: "Very graceful." }],
  },

  {
    id: 25,
    name: "Faux Fur Coat",
    brand: "Zara",
    category: "Coats",
    gender: "Women",
    price: 5999,
    originalPrice: 7499,
    discount: "20% OFF",
    rating: 4.8,
    reviewCount: 46,
    image:
      "https://i.pinimg.com/736x/75/fd/bf/75fdbf65a137a0adc13dddadb49477a7.jpg",
    isBestSeller: true,
    description: "Luxurious faux fur coat designed for winter fashion.",
    sizes: ["S", "M", "L"],
    colors: ["Brown", "Cream"],
    material: "Faux Fur",
    fit: "Relaxed Fit",
    careInstructions: ["Dry clean only"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 5–7 days",
    returnPolicy: "7-day easy returns",
    reviews: [
      { user: "Akhila", rating: 5, comment: "Super warm and stylish!" },
    ],
  },

  {
    id: 26,
    name: "Linen Summer Dress",
    brand: "H&M",
    category: "Dresses",
    gender: "Women",
    price: 2599,
    originalPrice: 3199,
    discount: "19% OFF",
    rating: 4.6,
    reviewCount: 92,
    image:
      "https://i.pinimg.com/736x/ac/1f/56/ac1f56382436f3cddc4bc4b360371dc3.jpg",
    isBestSeller: false,
    description: "Breathable linen dress perfect for hot summer days.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Sky Blue"],
    material: "Linen Blend",
    fit: "Regular Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Deepthi", rating: 4, comment: "Very comfortable." }],
  },

  {
    id: 27,
    name: "Wool Knit Cardigan",
    brand: "Uniqlo",
    category: "Cardigans",
    gender: "Women",
    price: 2899,
    originalPrice: 3599,
    discount: "19% OFF",
    rating: 4.7,
    reviewCount: 58,
    image:
      "https://i.pinimg.com/736x/ce/4a/9b/ce4a9b7e309185776f31414b0ccd7ab0.jpg",
    isBestSeller: true,
    description: "Warm wool-knit cardigan ideal for winter layering.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Brown"],
    material: "Wool Blend",
    fit: "Regular Fit",
    careInstructions: ["Hand wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Shalini", rating: 5, comment: "Very cozy." }],
  },

  {
    id: 28,
    name: "Ankle Strap Heels",
    brand: "Steve Madden",
    category: "Footwear",
    gender: "Women",
    price: 3499,
    originalPrice: 4299,
    discount: "18% OFF",
    rating: 4.6,
    reviewCount: 81,
    image:
      "https://i.pinimg.com/1200x/37/04/0b/37040b0c25c1244f86e1540e3caeb229.jpg",
    isBestSeller: true,
    description:
      "Elegant ankle strap heels suitable for parties and formal wear.",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Black", "Nude"],
    material: "Synthetic Leather",
    fit: "Comfort Fit",
    careInstructions: ["Wipe clean"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Kiran", rating: 4, comment: "Very stylish heels." }],
  },

  {
    id: 29,
    name: "Off-Shoulder Summer Top",
    brand: "Forever 21",
    category: "Tops",
    gender: "Women",
    price: 1499,
    originalPrice: 1999,
    discount: "25% OFF",
    rating: 4.5,
    reviewCount: 67,
    image:
      "https://i.pinimg.com/736x/6f/d3/1f/6fd31f404b3993e53257b6266e86b159.jpg",
    isBestSeller: false,
    description: "Lightweight off-shoulder top perfect for summer outings.",
    sizes: ["S", "M", "L"],
    colors: ["Floral", "White"],
    material: "Cotton Blend",
    fit: "Slim Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Nikita", rating: 4, comment: "Nice summer top." }],
  },

  {
    id: 30,
    name: "High-Waist Denim Skirt",
    brand: "Levi's",
    category: "Skirts",
    gender: "Women",
    price: 1999,
    originalPrice: 2499,
    discount: "20% OFF",
    rating: 4.6,
    reviewCount: 74,
    image:
      "https://i.pinimg.com/736x/d5/07/34/d50734d336149e5b0a25410f78d80744.jpg",
    isBestSeller: true,
    description: "Classic high-waist denim skirt for casual everyday wear.",
    sizes: ["26", "28", "30", "32"],
    colors: ["Blue"],
    material: "Denim Cotton",
    fit: "Regular Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Pallavi", rating: 5, comment: "Perfect fit!" }],
  },
  {
    id: 31,
    name: "Sleeveless Blouse",
    brand: "Zara",
    category: "Tops",
    gender: "Women",
    price: 1299,
    originalPrice: 1799,
    discount: "28% OFF",
    rating: 4.5,
    reviewCount: 61,
    image:
      "https://i.pinimg.com/1200x/f7/1c/bd/f71cbd683b3614a3a8dc5303f4c0be2a.jpg",
    isBestSeller: true,
    description:
      "Elegant sleeveless blouse perfect for office and casual wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    material: "Poly Crepe",
    fit: "Regular Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Harsha", rating: 5, comment: "Perfect office wear." }],
  },

  {
    id: 32,
    name: "Pleated Pants",
    brand: "H&M",
    category: "Pants",
    gender: "Women",
    price: 2499,
    originalPrice: 3199,
    discount: "22% OFF",
    rating: 4.7,
    reviewCount: 83,
    image:
      "https://i.pinimg.com/1200x/52/77/6a/52776a5628f9e6e65355400b65d9f0bb.jpg",
    isBestSeller: false,
    description: "Stylish pleated pants offering comfort and a tailored look.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Black"],
    material: "Poly Viscose",
    fit: "Tailored Fit",
    careInstructions: ["Machine wash gentle"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Radhika", rating: 5, comment: "Very classy fit." }],
  },

  {
    id: 33,
    name: "V-Neck Knit Sweater",
    brand: "Uniqlo",
    category: "Sweaters",
    gender: "Women",
    price: 1999,
    originalPrice: 2499,
    discount: "20% OFF",
    rating: 4.6,
    reviewCount: 96,
    image:
      "https://i.pinimg.com/736x/ef/ae/48/efae48ce6ac1bbef7ef752362eb718f0.jpg",
    isBestSeller: true,
    description: "Soft knit sweater with a flattering V-neck design.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "Grey"],
    material: "Cotton Knit Blend",
    fit: "Regular Fit",
    careInstructions: ["Hand wash recommended"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Sangeetha", rating: 4, comment: "Very soft fabric." }],
  },

  {
    id: 34,
    name: "Platform Sneakers",
    brand: "Nike",
    category: "Footwear",
    gender: "Women",
    price: 3499,
    originalPrice: 4299,
    discount: "18% OFF",
    rating: 4.5,
    reviewCount: 108,
    image:
      "https://i.pinimg.com/1200x/f2/58/05/f2580568d95bfa827278c0e6c63d4d2b.jpg",
    isBestSeller: true,
    description: "Trendy platform sneakers combining comfort and sporty style.",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["White", "Black"],
    material: "Mesh & Synthetic",
    fit: "Comfort Fit",
    careInstructions: ["Clean with damp cloth"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Keerthana", rating: 5, comment: "Very comfortable!" }],
  },

  {
    id: 35,
    name: "Tie-Dye T-Shirt",
    brand: "H&M",
    category: "T-Shirts",
    gender: "Women",
    price: 899,
    originalPrice: 1299,
    discount: "31% OFF",
    rating: 4.4,
    reviewCount: 54,
    image:
      "https://i.pinimg.com/1200x/d3/5e/1a/d35e1ab04a63c7b3ad8bfcd2819d922c.jpg",
    isBestSeller: false,
    description: "Casual tie-dye t-shirt for a relaxed everyday look.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Multicolor"],
    material: "100% Cotton",
    fit: "Relaxed Fit",
    careInstructions: ["Machine wash cold"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 3–5 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Nisha", rating: 4, comment: "Nice casual tee." }],
  },

  {
    id: 36,
    name: "Bohemian Maxi Skirt",
    brand: "Forever 21",
    category: "Skirts",
    gender: "Women",
    price: 3299,
    originalPrice: 3999,
    discount: "18% OFF",
    rating: 4.7,
    reviewCount: 79,
    image:
      "https://i.pinimg.com/736x/13/d1/2e/13d12e4480cd2445455da59bc4d7af44.jpg",
    isBestSeller: true,
    description: "Flowy bohemian maxi skirt ideal for festive and casual wear.",
    sizes: ["S", "M", "L"],
    colors: ["Brown", "Teal"],
    material: "Rayon Blend",
    fit: "Flowy Fit",
    careInstructions: ["Hand wash recommended"],
    availability: "In Stock",
    shippingInfo: "Free delivery in 4–6 days",
    returnPolicy: "7-day easy returns",
    reviews: [{ user: "Meenakshi", rating: 5, comment: "Beautiful design!" }],
  },
];
export default products;
